In [2]:
import pandas as pd

In [11]:
s=pd.Series([23,46,67,89,86])#single column

In [8]:
print(type(s))

<class 'pandas.core.series.Series'>

In [9]:
print(s)

0    23
1    46
2    67
3    89
4    86
dtype: int64

In [10]:
s

0    23
1    46
2    67
3    89
4    86
dtype: int64

In [12]:
s.dtype

dtype('int64')

In [3]:
s2=pd.Series([23,46,67,89,86],index=["Abhay","Kunal","Alok","Bittu","Ram"])

In [4]:
s2

Abhay    23
Kunal    46
Alok     67
Bittu    89
Ram      86
dtype: int64

In [15]:
s2["Abhay"]

np.int64(23)

In [29]:
print(s[0])#label represent in future version

23

C:\Users\Dipak Kumar\AppData\Local\Temp\ipykernel_1060\612857994.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])#label represent in future version

In [30]:
s.loc["Ram"] #for label data

np.int64(86)

In [28]:
s2.iloc[0] #for position

np.int64(23)

# CREATING DATAFRAME USING DICTIONARY

In [32]:
data={"name":["Abhay","Ram","Rohan","Rakesh","Mohan"],
      "age":[18,19,17,20,21],
      "City":["muz","pat","madh","nal","sam"]
     }

In [34]:
pd.DataFrame(data) # it genrate a data in tabular form

     name  age  City
0   Abhay   18   muz
1     Ram   19   pat
2   Rohan   17  madh
3  Rakesh   20   nal
4   Mohan   21   sam

In [35]:
df=pd.DataFrame(data)

In [36]:
df

     name  age  City
0   Abhay   18   muz
1     Ram   19   pat
2   Rohan   17  madh
3  Rakesh   20   nal
4   Mohan   21   sam

In [38]:
df.index # it shows index start and end

RangeIndex(start=0, stop=5, step=1)

In [42]:
df.columns

Index(['name', 'age', 'City'], dtype='object')

In [11]:
df=pd.read_excel("data.xlsx")

In [12]:
df

       Name School  Marks
0     Abhay   GSPS     83
1     Kunal    RMV     81
2  Himanshu   GSPS     78
3       Ram    STM     90
4    Mahesh    LTM     98

In [16]:
df=pd.read_csv("data.csv")#read from csv

In [15]:
df

       Name School  Marks
0     Abhay   GSPS     83
1     Kunal    RMV     81
2  Himanshu   GSPS     78
3       Ram    STM     90
4    Mahesh    LTM     98