In [2]:
import pandas as pd

1.) CREATING DATAFRAME USING LIST

In [4]:
data=[["Abhay",85],["Ram",69],["Pankaj",90],["shubham",82]]

In [12]:
data

[['Abhay', 85], ['Ram', 69], ['Pankaj', 90], ['shubham', 82]]

In [7]:
pd.DataFrame(data) # without data label

         0   1
0    Abhay  85
1      Ram  69
2   Pankaj  90
3  shubham  82

In [5]:
pd.DataFrame(data,columns=["Name","marks"]) # with data label

      Name  marks
0    Abhay     85
1      Ram     69
2   Pankaj     90
3  shubham     82

2.) USING DICTIONARY FRAMING DATA IN DATA FRAME

In [9]:
data_2={"Name":["A","B","C"],
        "Age":[23,25,27]
       }

In [10]:
pd.DataFrame(data_2) # using dictionary data

  Name  Age
0    A   23
1    B   25
2    C   27

3.) USING NumPy FRAMING DATA IN DATAFRAME

In [11]:
import numpy as np

In [26]:
arr=np.array([[1,2],[3,4]])

In [28]:
pd.DataFrame(arr,columns=["A","B"])

   A  B
0  1  2
1  3  4

ACCESS DATA OF EXCEL FILE

In [6]:
df = pd.read_excel("data.xlsx.xlsx") # access data of excel file
print(df)

       Name School  Marks
0     Abhay   GSPS     83
1     Kunal    RMV     81
2  Himanshu   GSPS     78
3       Ram    STM     90
4    Mahesh    LTM     98

ACCESS DATA OF JSON FILE

In [10]:
df=pd.read_json("data.json.json") # Access data of json file

In [9]:
df

    name  Age
0  Abhay   18
1  Kunal   19

In [17]:
df=pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv") # access iris dataset

In [18]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [19]:
df.head() # gives first five row of data

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [20]:
df.tail() # it gives last five row of data

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [24]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [21]:
print(df.columns)

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [22]:
df.index

RangeIndex(start=0, stop=244, step=1)