In [1]:
import pandas as pd

In [2]:
df=pd.read_excel("BollywoodData.xlsx")

In [4]:
df

,Actor,Film,Year,Genre,BoxOffice (INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [10]:
df["Actor"] #single column

0         Shah Rukh Khan
1            Salman Khan
2             Aamir Khan
3          Ranbir Kapoor
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
9          Kartik Aaryan
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: object

In [13]:
df["Actor"][8]#specific actor

'Akshay Kumar'

In [6]:
type(df)

pandas.core.frame.DataFrame

In [11]:
df[["Actor","IMDb"]]# multiple column

                 Actor  IMDb
0       Shah Rukh Khan   7.2
1          Salman Khan   6.0
2           Aamir Khan   8.4
3        Ranbir Kapoor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khurrana   8.3
6        Rajkummar Rao   7.5
7       Hrithik Roshan   6.5
8         Akshay Kumar   7.0
9        Kartik Aaryan   5.9
10        Varun Dhawan   6.1
11       Vicky Kaushal   8.2

In [12]:
df

,Actor,Film,Year,Genre,BoxOffice (INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [6]:
df.loc[3] #it gives data using labeled row,eg. df.loc["a"]

Actor                    Ranbir Kapoor
Film                        Brahmastra
Year                              2022
Genre                          Fantasy
BoxOffice (INR Crore)              431
IMDb                               5.6
Name: 3, dtype: object

In [8]:
df.iloc[3]#it gives data using position number

Actor                    Ranbir Kapoor
Film                        Brahmastra
Year                              2022
Genre                          Fantasy
BoxOffice (INR Crore)              431
IMDb                               5.6
Name: 3, dtype: object

In [31]:
print(df.loc[4,"IMDb"]) # row represent before comma , column represent after comma

7.0

In [36]:
df.iloc[4,1]#row represent before comma , column represent after comma using index

'Padmaavat'

In [38]:
df.loc[0:2]# 2 also included in this case

,Actor,Film,Year,Genre,BoxOffice (INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [41]:
df.loc[0:2,["Actor","IMDb","Film"]]

            Actor  IMDb             Film
0  Shah Rukh Khan   7.2          Pathaan
1     Salman Khan   6.0  Tiger Zinda Hai
2      Aamir Khan   8.4           Dangal

In [43]:
df.iloc[0:3,0:3] # here in iloc case 3 is excluded

            Actor             Film  Year
0  Shah Rukh Khan          Pathaan  2023
1     Salman Khan  Tiger Zinda Hai  2017
2      Aamir Khan           Dangal  2016

In [46]:
df.at[0,"Actor"]#fast access for particular element access

'Shah Rukh Khan'

In [10]:
df["IMDb"]>6 #it makes boolean series

0      True
1     False
2      True
3     False
4      True
5      True
6      True
7      True
8      True
9     False
10     True
11     True
Name: IMDb, dtype: bool

In [12]:
df[df["IMDb"]>6] # it print row where condition is true

,Actor,Film,Year,Genre,BoxOffice (INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

# NOTES: Single square bracket for single column and for mutiple column for double square bracket

In [14]:
df[df["IMDb"]>6]["Actor"] # for specific column required

0         Shah Rukh Khan
2             Aamir Khan
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: object

In [10]:
df[df["IMDb"]>6][["Actor","Year"]] # for multiple column required

                 Actor  Year
0       Shah Rukh Khan  2023
2           Aamir Khan  2016
4        Ranveer Singh  2018
5   Ayushmann Khurrana  2018
6        Rajkummar Rao  2018
7       Hrithik Roshan  2019
8         Akshay Kumar  2019
10        Varun Dhawan  2017
11       Vicky Kaushal  2019

In [12]:
df[(df["IMDb"]>7) & (df["Year"]>=2019)]

,Actor,Film,Year,Genre,BoxOffice (INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [64]:
df[(df["IMDb"]>6) | (df["Year"]>2018)]

,Actor,Film,Year,Genre,BoxOffice (INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

SPECIAL METHOD FOR CONDITION CHECK

In [67]:
df.query("Year>2019")#SPECIAL METHOD

,Actor,Film,Year,Genre,BoxOffice (INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa,2022,Horror Comedy,266,5.9

In [79]:
# df.query("Year > 2018 & IMDb >7")#bad
df.query("Year > 2018 and IMDb >7")#good

,Actor,Film,Year,Genre,BoxOffice (INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [83]:
df.query("Year > 2017 and 6 < IMDb < 7")

            Actor Film  Year   Genre  BoxOffice (INR Crore)  IMDb
7  Hrithik Roshan  War  2019  Action                    475   6.5

# NOTES: pandas doesn't gurantee you get copy , make use .copy() for no risk
# Tips: whenever you need to work with segment of part then always use .copy()

In [99]:
df2=df[["Actor","Film"]].copy()

In [89]:
df2

                 Actor                      Film
0       Shah Rukh Khan                   Pathaan
1                Abhay           Tiger Zinda Hai
2           Aamir Khan                    Dangal
3        Ranbir Kapoor                Brahmastra
4        Ranveer Singh                 Padmaavat
5   Ayushmann Khurrana                 Andhadhun
6        Rajkummar Rao                     Stree
7       Hrithik Roshan                       War
8         Akshay Kumar                Good Newwz
9        Kartik Aaryan           Bhool Bhulaiyaa
10        Varun Dhawan     Badrinath Ki Dulhania
11       Vicky Kaushal  Uri: The Surgical Strike

In [96]:
df2.loc[1,"Actor"]="Kunal"

C:\Users\Dipak Kumar\AppData\Local\Temp\ipykernel_4656\2345676338.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.loc[1,"Actor"]="Kunal"

In [97]:
df2

                 Actor                      Film
0       Shah Rukh Khan                   Pathaan
1                Kunal           Tiger Zinda Hai
2           Aamir Khan                    Dangal
3        Ranbir Kapoor                Brahmastra
4        Ranveer Singh                 Padmaavat
5   Ayushmann Khurrana                 Andhadhun
6        Rajkummar Rao                     Stree
7       Hrithik Roshan                       War
8         Akshay Kumar                Good Newwz
9        Kartik Aaryan           Bhool Bhulaiyaa
10        Varun Dhawan     Badrinath Ki Dulhania
11       Vicky Kaushal  Uri: The Surgical Strike

In [16]:
df

,Actor,Film,Year,Genre,BoxOffice (INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2