In [2]:
import pandas as pd

In [4]:
df=pd.read_csv("data_cleaning_sample.csv")

In [5]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [6]:
df.isnull() # it represent where the value/data is null (if data is null/empty represent True and False is right)

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [7]:
df.isnull().sum() # it shows total null value per column(Fasle=0,True=1)

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [11]:
df.dropna() # remove the row having missing value (by default axis = 0)

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [17]:
df.dropna(axis=1) # remove the missing column value

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [19]:
df.fillna(0) # all at the missing value nan/empty value assign at 0

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [12]:
df.fillna(method="ffill") # forward Fill : in this data fill at empty/null value according to upwardData

C:\Users\Dipak Kumar\AppData\Local\Temp\ipykernel_5844\4137889992.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill") # forward Fill : in this data fill at empty/null value according to upwardData

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [22]:
df.fillna(method="bfill") # in this data fill at empty/null value according to backData

C:\Users\Dipak Kumar\AppData\Local\Temp\ipykernel_12404\1742816711.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill") # in this data fill at empty/null value according to backData

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

# df.fillna(method="ffill") --- old version or 
# df.ffill() ---best new version

In [29]:
df.ffill() # forward fill

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [28]:
df.bfill() # backward fill

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [18]:
df.duplicated() # if repeated value/data comes then it show True other wise False (False show everything is ok) row wise check

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [34]:
df.drop_duplicates() # drop all duplicate row value/data not empty value

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [36]:
df.duplicated(subset=["Name","Age"]) # pair wise check duplicate

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

# STRING METHOD

In [40]:
df["Name"].str.lower()

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: object

In [13]:
df["City"].str.contains("Delhi",case=True) # it check Delhi present in City column or not
#True represent it present in City column

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [50]:
type(df["City"].str.contains("Delhi",case=True)) # it is pandas series

pandas.core.series.Series

In [15]:
df["Email"].str.split("@") # labeling all row into list

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
3      [charlie, example]
4    [david, example.com]
5       [eve, domain.com]
6    [alice, example.com]
7    [alice, example.com]
8      [charlie, example]
Name: Email, dtype: object

In [14]:
df["Email"].str.split("@")[0]

['alice', 'example.com']

In [17]:
type(df["Email"].str.split("@")[0])

list

# TYPE CONVERSION

In [58]:
df2=df.dropna().copy() # always work with dot copy

In [60]:
df2

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [66]:
df2["Age"]=df2["Age"].astype(int)

In [67]:
df2

    Name  Age         City Gender              Email   Join Date
0  Alice   25     New York      F  alice@example.com  01-05-2021
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
4  David   22       Mumbai      M  david@example.com  12-11-2019
6  Alice   25     New York      F  alice@example.com  01-05-2021
7  Alice   25     New York      F  alice@example.com  01-05-2021

# Applying Functions

In [73]:
# def isminor(x):
#     return "Adult" if x>=25 else "minor"
# df2["Age Group"]=df2["Age"].apply(isminor)    

# or

df2["Age Group"]=df2["Age"].apply(lambda x : "Adult" if x >= 25 else "minor")

In [74]:
df2

    Name  Age         City Gender              Email   Join Date Age Group
0  Alice   25     New York      F  alice@example.com  01-05-2021     Adult
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020     Adult
4  David   22       Mumbai      M  david@example.com  12-11-2019     minor
6  Alice   25     New York      F  alice@example.com  01-05-2021     Adult
7  Alice   25     New York      F  alice@example.com  01-05-2021     Adult

In [78]:
gender_map={"M":"Male","F":"Female","0":"Other"}
df2["Gender"]=df2["Gender"].map(gender_map) # in this case we replace all value

In [79]:
df2

    Name  Age         City Gender              Email   Join Date Age Group
0  Alice   25     New York    NaN  alice@example.com  01-05-2021     Adult
2    Bob   30  Los Angeles    NaN    bob@example.com  15-06-2020     Adult
4  David   22       Mumbai    NaN  david@example.com  12-11-2019     minor
6  Alice   25     New York    NaN  alice@example.com  01-05-2021     Adult
7  Alice   25     New York    NaN  alice@example.com  01-05-2021     Adult

In [84]:
df2["City"]=df2["City"].replace({"Mumbai":"Bihar","New York":"Tokyo"})

In [85]:
df2

    Name  Age         City Gender              Email   Join Date Age Group
0  Alice   25        Tokyo    NaN  alice@example.com  01-05-2021     Adult
2    Bob   30  Los Angeles    NaN    bob@example.com  15-06-2020     Adult
4  David   22        Bihar    NaN  david@example.com  12-11-2019     minor
6  Alice   25        Tokyo    NaN  alice@example.com  01-05-2021     Adult
7  Alice   25        Tokyo    NaN  alice@example.com  01-05-2021     Adult