In [2]:
import pandas as pd

# Sample DataFrame

In [3]:
data={
    "Name":["Abhay","Kunal","Ram","Rohan","Alok"],
    "Math":[96,89,91,84,86],
    "Physic":[86,81,88,81,79],
    "English":[82,79,83,75,75],
}

df=pd.DataFrame(data)

In [4]:
df

    Name  Math  Physic  English
0  Abhay    96      86       82
1  Kunal    89      81       79
2    Ram    91      88       83
3  Rohan    84      81       75
4   Alok    86      79       75

# -- melt() method

Syntax : df.melt(id_vars=None, value_vars=None, var_name=None, value_name="value", col_level=None)

In [5]:
df2=df.melt(id_vars=["Name"], value_vars=["Math", "Physic", "English"], 
            var_name="Subject", value_name="Score")

In [6]:
df2

     Name  Subject  Score
0   Abhay     Math     96
1   Kunal     Math     89
2     Ram     Math     91
3   Rohan     Math     84
4    Alok     Math     86
5   Abhay   Physic     86
6   Kunal   Physic     81
7     Ram   Physic     88
8   Rohan   Physic     81
9    Alok   Physic     79
10  Abhay  English     82
11  Kunal  English     79
12    Ram  English     83
13  Rohan  English     75
14   Alok  English     75

# -- pivot()
Syntax :df.pivot(index=None, columns=None, values=None)

In [20]:
df2.pivot(index="Name", columns="Subject", values="Score")

Subject  English  Math  Physic
Name
Abhay         82    96      86
Alok          75    86      79
Kunal         79    89      81
Ram           83    91      88
Rohan         75    84      81