In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({
    "Department": ["HR", "HR", "IT", "IT", "Marketing", "Marketing", "Sales", "Sales"],
    "Team": ["A", "A", "B", "B", "C", "C", "D", "D"],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F"],
    "Salary": [85, 90, 78, 85, 92, 88, 75, 80],
    "Age": [23, 25, 30, 22, 28, 26, 21, 27],
    "JoinDate": pd.to_datetime([
        "2020-01-10", "2020-02-15", "2021-03-20", "2021-04-10",
        "2020-05-30", "2020-06-25", "2021-07-15", "2021-08-01"
    ])
})  
# pd.to_datetime(["2020-01-10", "2020-02-15"]) # converting dateString into actual dateTime formet

In [4]:
df

  Department Team Gender  Salary  Age   JoinDate
0         HR    A      M      85   23 2020-01-10
1         HR    A      F      90   25 2020-02-15
2         IT    B      M      78   30 2021-03-20
3         IT    B      F      85   22 2021-04-10
4  Marketing    C      M      92   28 2020-05-30
5  Marketing    C      F      88   26 2020-06-25
6      Sales    D      M      75   21 2021-07-15
7      Sales    D      F      80   27 2021-08-01

In [13]:
df.groupby("Department")["Salary"].mean() # it is a type of series

Department
HR           87.5
IT           81.5
Marketing    90.0
Sales        77.5
Name: Salary, dtype: float64

In [11]:
df.groupby("Gender")["Salary"].mean()

Gender
F    85.75
M    82.50
Name: Salary, dtype: float64

In [10]:
type(df.groupby("Department")["Salary"].mean())

pandas.core.series.Series

# .agg() and .aggregate() both are same

# Example :-

In [15]:
df.groupby("Gender")["Salary"].agg(["mean","max","min"])

         mean  max  min
Gender
F       85.75   90   80
M       82.50   92   75

In [27]:
df.groupby("Department")["Salary"].agg(["mean","max","min"])

            mean  max  min
Department
HR          87.5   90   85
IT          81.5   85   78
Marketing   90.0   92   88
Sales       77.5   80   75

In [14]:
df.groupby("Department")["Salary"].aggregate(["mean","max","min"])

            mean  max  min
Department
HR          87.5   90   85
IT          81.5   85   78
Marketing   90.0   92   88
Sales       77.5   80   75

# same

In [18]:
df.groupby("Department")["Salary"].count()

Department
HR           2
IT           2
Marketing    2
Sales        2
Name: Salary, dtype: int64

In [23]:
df.groupby("Department")["Salary"].agg(
    Average_Salary="mean",Highest_Salary="max") #

            Average_Salary  Highest_Salary
Department
HR                    87.5              90
IT                    81.5              85
Marketing             90.0              92
Sales                 77.5              80

In [45]:
df["TeamAvg"] = df.groupby("Team")["Salary"].transform("mean")

In [46]:
df

  Department Team Gender  Salary  Age   JoinDate  Team Avg  Team-Avg  TeamAvg
0         HR    A      M      85   23 2020-01-10      87.5      87.5     87.5
1         HR    A      F      90   25 2020-02-15      87.5      87.5     87.5
2         IT    B      M      78   30 2021-03-20      81.5      81.5     81.5
3         IT    B      F      85   22 2021-04-10      81.5      81.5     81.5
4  Marketing    C      M      92   28 2020-05-30      90.0      90.0     90.0
5  Marketing    C      F      88   26 2020-06-25      90.0      90.0     90.0
6      Sales    D      M      75   21 2021-07-15      77.5      77.5     77.5
7      Sales    D      F      80   27 2021-08-01      77.5      77.5     77.5

In [17]:
#.filter() use when need some filter row , Here x is whole group
df.groupby("Team").filter(lambda x: x["Salary"].mean() >85)

  Department Team Gender  Salary  Age   JoinDate
0         HR    A      M      85   23 2020-01-10
1         HR    A      F      90   25 2020-02-15
4  Marketing    C      M      92   28 2020-05-30
5  Marketing    C      F      88   26 2020-06-25