In [3]:
import pandas as pd

In [4]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [3]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [4]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [15]:
# on is parameter telling about on which basis you merge the data
# by default here how = inner
pd.merge(employees,departments,on="DeptID") # inner join

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [17]:
# This is left join , to preserve all row of data frame employees
pd.merge(employees,departments,on="DeptID",how="left")

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [6]:
# This is right join , to preserve all row of data frame departments
pd.merge(employees,departments,on="DeptID",how="right") # right join

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [7]:
# Here all id is considered , it gives all row of ememployees and departments
# and where data is not clr on that place NaN 
pd.merge(employees,departments,on="DeptID",how="outer") # outer join

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

# Concatenating DataFrame

In [8]:
df1=pd.DataFrame({"Name":["Abhay","Alok"]})
df2=pd.DataFrame({"Name":["Ram","Rohan"]})

In [9]:
pd.concat([df1,df2]) # by default horizontal concatenate , here axis=0

    Name
0  Abhay
1   Alok
0    Ram
1  Rohan

In [37]:
pd.concat([df1,df2],axis=1) # vertical concatenate

    Name   Name
0  Abhay    Ram
1   Alok  Rohan

In [11]:
df1=pd.DataFrame({"Name":["Abhay","Alok"],"Age":[18,19]})
df2=pd.DataFrame({"Name":["Ram","Rohan"],"Grade":["A","A+"]})

In [12]:
pd.concat([df1,df2])

    Name   Age Grade
0  Abhay  18.0   NaN
1   Alok  19.0   NaN
0    Ram   NaN     A
1  Rohan   NaN    A+

In [41]:
pd.concat([df1,df2],axis=1)

    Name  Age   Name Grade
0  Abhay   18    Ram     A
1   Alok   19  Rohan    A+