In [3]:
import pandas as pd

# Reading excel file

In [6]:
df=pd.read_excel("BollywoodData.xlsx")

In [7]:
df

,Actor,Film,Year,Genre,BoxOffice (INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [8]:
df=df[df["IMDb"]>6.0]

In [9]:
df

,Actor,Film,Year,Genre,BoxOffice (INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

# Writing a data into excel

In [10]:
# update ?
#-- IMDb>6.0 file get updated
df.to_excel("data_updates.xlsx")

In [19]:
# use when no need of index
# always make sure old excel/csv file close/saved
df.to_excel("data_updates.xlsx",index=False) # here index get remove

Similary same concept for reading and writing in csv file

In [29]:
df=pd.read_json("jsondata02.json")

In [30]:
df

   id   name                                  address
0   1  Alice   {'city': 'Delhi', 'zipcode': '110001'}
1   2    Bob  {'city': 'Mumbai', 'zipcode': '400001'}

In [16]:
data=[
    {"id": 1, "name": "Alice", "address": {"city": "Delhi", "zipcode": "110001"}},
    {"id": 2, "name": "Bob", "address": {"city": "Mumbai", "zipcode": "400001"}}
]

In [18]:
pd.json_normalize(data)

   id   name address.city address.zipcode
0   1  Alice        Delhi          110001
1   2    Bob       Mumbai          400001

# Reading csv file

In [21]:
pd.read_csv("csvfile01.csv")

       Name School  Marks
0     Abhay   GSPS     83
1     Kunal    RMV     81
2  Himanshu   GSPS     78
3       Ram    STM     90
4    Mahesh    LTM     98

In [24]:
pd.read_csv("csvfile01.csv",usecols=["Name","Marks"]) # for specific column is needed

       Name  Marks
0     Abhay     83
1     Kunal     81
2  Himanshu     78
3       Ram     90
4    Mahesh     98

In [27]:
df2=pd.read_csv("csvfile01.csv",usecols=["Name","Marks","School"],nrows=3)# upto 2 row 3 is not considered

In [28]:
df2

       Name School  Marks
0     Abhay   GSPS     83
1     Kunal    RMV     81
2  Himanshu   GSPS     78

| File Type     | Read Method         | Write Method      |
| ------------- | ------------------- | ----------------- |
| CSV           | `pd.read_csv()`     | `df.to_csv()`     |
| Excel (.xlsx) | `pd.read_excel()`   | `df.to_excel()`   |
| JSON          | `pd.read_json()`    | `df.to_json()`    |
| HTML Table    | `pd.read_html()`    | `df.to_html()`    |
| XML           | `pd.read_xml()`     | `df.to_xml()`     |
| SQL Database  | `pd.read_sql()`     | `df.to_sql()`     |
| Parquet       | `pd.read_parquet()` | `df.to_parquet()` |
| Pickle        | `pd.read_pickle()`  | `df.to_pickle()`  |