In [5]:
import pandas as pd

In [66]:
import numpy as np

In [7]:
df=pd.read_csv("FIDE-DataSet.zip")

In [8]:
df

,id,name,fed,sex,title,wtitle,otitle,foa,rating,games,k,bday
0,53707043,A Darshil,IND,M,NaN,NaN,NaN,NaN,1412,4,40,2013
1,53200465,"A F M Ehteshamul, Hoque (tuhin",BAN,M,NaN,NaN,NaN,NaN,1797,0,40,1977
2,5716365,"A Hamid, Harman",MAS,M,NaN,NaN,NaN,NaN,1552,0,20,1970
3,53200553,A I Sabbir,BAN,M,NaN,NaN,NaN,NaN,1607,0,40,1995
4,5045886,"A K, Kalshyan",IND,M,NaN,NaN,NaN,NaN,1747,0,20,1964
...,...,...,...,...,...,...,...,...,...,...,...,...
201010,4600410,"Zysk, Robert",GER,M,IM,NaN,NaN,NaN,2373,0,10,1966
201011,1141589,"Zysko, Jan",POL,M,NaN,NaN,NaN,NaN,2129,6,20,1990
201012,80411533,"Zyskowski, Jean-Luc",FRA,M,NaN,NaN,NaN,NaN,1517,6,20,1972
201013,21836060,"Zyto, Karol",POL,M,NaN,NaN,NaN,NaN,1748,0,20,2006
201014,55812104,"Zyuryunina, Tatiana",RUS,F,NaN,NaN,NaN,NaN,1416,0,40,2013

| Column     | Meaning                                                                                    |
| ---------- | ------------------------------------------------------------------------------------------ |
| **id**     | Player ka unique ID                                                                        |
| **name**   | Player ka naam                                                                             |
| **fed**    | Federation/Country code (IND = India, BAN = Bangladesh, MAS = Malaysia)                    |
| **sex**    | Gender (M = Male, F = Female)                                                              |
| **title**  | Chess title (GM = Grandmaster, IM = International Master, FM = FIDE Master, NA = No title) |
| **wtitle** | Women's title (WGM, WIM, WFM, etc.)                                                        |
| **otitle** | Other official titles (agar koi ho)                                                        |
| **foa**    | FIDE Online Arena title (Arena Grandmaster, Arena Master, etc.)                            |
| **rating** | Chess rating (jitni zyada, utna strong player)                                             |
| **games**  | Rated games ki sankhya                                                                     |
| **k**      | K-factor (rating kitni tezi se change hogi)                                                |
| **bday**   | Birth year                                                                                 |

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201015 entries, 0 to 201014
Data columns (total 12 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   id      201015 non-null  int64
 1   name    201015 non-null  object
 2   fed     201015 non-null  object
 3   sex     201015 non-null  object
 4   title   12649 non-null   object
 5   wtitle  2259 non-null    object
 6   otitle  2018 non-null    object
 7   foa     4308 non-null    object
 8   rating  201015 non-null  int64
 9   games   201015 non-null  int64
 10  k       201015 non-null  int64
 11  bday    201015 non-null  int64
dtypes: int64(5), object(7)
memory usage: 18.4+ MB

In [10]:
df["bday"].min()

1900

In [11]:
df["bday"].max()

2021

In [12]:
df.tail()

,id,name,fed,sex,title,wtitle,otitle,foa,rating,games,k,bday
201010,4600410,"Zysk, Robert",GER,M,IM,NaN,NaN,NaN,2373,0,10,1966
201011,1141589,"Zysko, Jan",POL,M,NaN,NaN,NaN,NaN,2129,6,20,1990
201012,80411533,"Zyskowski, Jean-Luc",FRA,M,NaN,NaN,NaN,NaN,1517,6,20,1972
201013,21836060,"Zyto, Karol",POL,M,NaN,NaN,NaN,NaN,1748,0,20,2006
201014,55812104,"Zyuryunina, Tatiana",RUS,F,NaN,NaN,NaN,NaN,1416,0,40,2013

In [17]:
df2=df.query("fed=='IND'")

In [18]:
df2

,id,name,fed,sex,title,wtitle,otitle,foa,rating,games,k,bday
0,53707043,A Darshil,IND,M,NaN,NaN,NaN,NaN,1412,4,40,2013
4,5045886,"A K, Kalshyan",IND,M,NaN,NaN,NaN,NaN,1747,0,20,1964
7,33454710,A. HUDSON,IND,M,NaN,NaN,NaN,AFM,1644,0,40,2013
11,33404011,Aabha Milind Gavkar,IND,F,NaN,NaN,NaN,NaN,1519,0,20,2004
12,88105563,Aabhas Kumar Srivastava,IND,M,NaN,NaN,NaN,NaN,1807,0,40,2009
...,...,...,...,...,...,...,...,...,...,...,...,...
200496,42909303,Zonunsanga T,IND,M,NaN,NaN,NaN,NaN,1643,0,40,1985
200545,46689893,Zosangluaia,IND,M,NaN,NaN,NaN,NaN,1604,0,40,1962
200549,42902905,Zothanhlira Royte,IND,M,NaN,NaN,NaN,NaN,1571,0,40,2007
200550,53109492,Zothanpuia Hnamte,IND,M,NaN,NaN,NaN,NaN,1720,0,40,1976
200665,54700472,Zubair Haider,IND,M,NaN,NaN,NaN,NaN,1486,5,40,2010

In [19]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16445 entries, 0 to 200665
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      16445 non-null  int64
 1   name    16445 non-null  object
 2   fed     16445 non-null  object
 3   sex     16445 non-null  object
 4   title   472 non-null    object
 5   wtitle  122 non-null    object
 6   otitle  160 non-null    object
 7   foa     1260 non-null   object
 8   rating  16445 non-null  int64
 9   games   16445 non-null  int64
 10  k       16445 non-null  int64
 11  bday    16445 non-null  int64
dtypes: int64(5), object(7)
memory usage: 1.6+ MB

In [20]:
df.index

RangeIndex(start=0, stop=201015, step=1)

In [21]:
df2["title"]

0         NaN
4         NaN
7         NaN
11        NaN
12        NaN
         ...
200496    NaN
200545    NaN
200549    NaN
200550    NaN
200665    NaN
Name: title, Length: 16445, dtype: object

In [24]:
df2.query("sex=='M' and rating > 2500")

,id,name,fed,sex,title,wtitle,otitle,foa,rating,games,k,bday
2155,5018471,"Adhiban, B.",IND,M,GM,NaN,NaN,NaN,2534,0,10,1992
2339,35042025,Aditya Mittal,IND,M,GM,NaN,NaN,NaN,2560,9,10,2006
7612,5000017,"Anand, Viswanathan",IND,M,GM,NaN,NaN,NaN,2743,0,10,1969
9766,5072786,"Aravindh, Chithambaram VR.",IND,M,GM,NaN,NaN,NaN,2723,8,10,1999
10716,25072846,Aronyak Ghosh,IND,M,IM,NaN,NaN,NaN,2514,0,10,2003
11229,5084423,Aryan Chopra,IND,M,GM,NaN,NaN,NaN,2634,9,10,2001
20346,46634827,Bharath Subramaniyam H,IND,M,GM,NaN,NaN,NaN,2562,18,10,2007
50403,35009192,Erigaisi Arjun,IND,M,GM,NaN,NaN,NaN,2776,0,10,2003
58364,5002150,"Ganguly, Surya Shekhar",IND,M,GM,NaN,NaN,NaN,2566,9,10,1983
61459,5045207,"Ghosh, Diptayan",IND,M,GM,NaN,NaN,NaN,2576,8,10,1998
64360,5015693,Gopal G.N.,IND,M,GM,NaN,NaN,NaN,2539,17,10,1989
67122,46616543,Gukesh D,IND,M,GM,NaN,NaN,NaN,2776,0,10,2006
67563,5010608,"Gupta, Abhijeet",IND,M,GM,NaN,NaN,NaN,2535,0,10,1989
70032,5007003,"Harikrishna, Pentala",IND,M,GM,NaN,NaN,NaN,2709,0,10,1986
70034,5081483,Harikrishnan.A.Ra,IND,M,IM,NaN,NaN,NaN,2504,27,10,2001
70262,5078776,Harsha Bharathakoti,IND,M,GM,NaN,NaN,NaN,2513,8,10,2000
76620,45015775,Ilamparthi A R,IND,M,IM,NaN,NaN,NaN,2515,18,10,2009
77100,25002767,"Iniyan, Pa",IND,M,GM,NaN,NaN,NaN,2586,27,10,2002
85316,25006479,Karthik Venkataraman,IND,M,GM,NaN,NaN,NaN,2556,20,10,1999
85346,5074452,"Karthikeyan, Murali",IND,M,GM,NaN,NaN,NaN,2658,10,10,1999
96592,5024595,Lalit Babu M R,IND,M,GM,NaN,NaN,NaN,2502,9,10,1993
114201,35028561,"Mendonca, Leon Luke",IND,M,GM,NaN,NaN,NaN,2606,19,10,2006
117140,5057000,"Mitrabha, Guha",IND,M,GM,NaN,NaN,NaN,2515,0,10,2001
124292,5058422,Narayanan S L,IND,M,GM,NaN,NaN,NaN,2595,9,10,1998
127095,25092340,Nihal Sarin,IND,M,GM,NaN,NaN,NaN,2692,0,10,2004
142407,25059530,Praggnanandhaa R,IND,M,GM,NaN,NaN,NaN,2779,0,10,2005
142538,46626786,Pranav Anand,IND,M,GM,NaN,NaN,NaN,2590,20,10,2006
142596,25060783,"Pranav, V",IND,M,GM,NaN,NaN,NaN,2597,10,10,2006
142627,35028600,Pranesh M,IND,M,GM,NaN,NaN,NaN,2589,10,10,2006
144194,5061245,"Puranik, Abhimanyu",IND,M,GM,NaN,NaN,NaN,2635,0,10,2000
145933,35007394,Raja Rithvik R,IND,M,GM,NaN,NaN,NaN,2553,19,10,2004
155630,35093487,"Sadhwani, Raunak",IND,M,GM,NaN,NaN,NaN,2676,9,10,2005
157343,35080580,Samant Aditya S,IND,M,GM,NaN,NaN,NaN,2517,19,10,2006
158644,5097010,Sankalp Gupta,IND,M,GM,NaN,NaN,NaN,2546,0,10,2003
159844,5004985,"Sasikiran, Krishnan",IND,M,GM,NaN,NaN,NaN,2524,10,10,1981
163861,5021596,"Sethuraman, S.P.",IND,M,GM,NaN,NaN,NaN,2569,9,10,1993
184939,5045185,"Vaibhav, Suri",IND,M,GM,NaN,NaN,NaN,2568,0,10,1997
189352,5029465,"Vidit, Santosh Gujrathi",IND,M,GM,NaN,NaN,NaN,2720,0,10,1994
189524,25012215,Vignesh N R,IND,M,GM,NaN,NaN,NaN,2516,17,10,1998
190425,25012223,Visakh N R,IND,M,GM,NaN,NaN,NaN,2553,0,10,1999

In [25]:
df2.query("sex=='F' and rating > 2500")

,id,name,fed,sex,title,wtitle,otitle,foa,rating,games,k,bday
90819,5008123,"Koneru, Humpy",IND,F,GM,WGM,NaN,NaN,2535,12,10,1987

In [38]:
df2[(df2["bday"]>=2005) & (df2["title"]=="GM") & (df2["rating"]>2500)][["name","title","rating" ,"bday"]]

                          name title  rating  bday
2339             Aditya Mittal    GM    2560  2006
20346   Bharath Subramaniyam H    GM    2562  2007
67122                 Gukesh D    GM    2776  2006
114201     Mendonca, Leon Luke    GM    2606  2006
142407        Praggnanandhaa R    GM    2779  2005
142538            Pranav Anand    GM    2590  2006
142596               Pranav, V    GM    2597  2006
142627               Pranesh M    GM    2589  2006
155630        Sadhwani, Raunak    GM    2676  2005
157343         Samant Aditya S    GM    2517  2006

In [39]:
df2[(df2["bday"]>=2005) & (df2["title"]=="GM") & (df2["rating"]>2500)]

,id,name,fed,sex,title,wtitle,otitle,foa,rating,games,k,bday
2339,35042025,Aditya Mittal,IND,M,GM,NaN,NaN,NaN,2560,9,10,2006
20346,46634827,Bharath Subramaniyam H,IND,M,GM,NaN,NaN,NaN,2562,18,10,2007
67122,46616543,Gukesh D,IND,M,GM,NaN,NaN,NaN,2776,0,10,2006
114201,35028561,"Mendonca, Leon Luke",IND,M,GM,NaN,NaN,NaN,2606,19,10,2006
142407,25059530,Praggnanandhaa R,IND,M,GM,NaN,NaN,NaN,2779,0,10,2005
142538,46626786,Pranav Anand,IND,M,GM,NaN,NaN,NaN,2590,20,10,2006
142596,25060783,"Pranav, V",IND,M,GM,NaN,NaN,NaN,2597,10,10,2006
142627,35028600,Pranesh M,IND,M,GM,NaN,NaN,NaN,2589,10,10,2006
155630,35093487,"Sadhwani, Raunak",IND,M,GM,NaN,NaN,NaN,2676,9,10,2005
157343,35080580,Samant Aditya S,IND,M,GM,NaN,NaN,NaN,2517,19,10,2006

In [41]:
df.query("rating >=2700")

,id,name,fed,sex,title,wtitle,otitle,foa,rating,games,k,bday
986,14204118,"Abdusattorov, Nodirbek",UZB,M,GM,NaN,NaN,NaN,2771,0,10,2004
7612,5000017,"Anand, Viswanathan",IND,M,GM,NaN,NaN,NaN,2743,0,10,1969
9766,5072786,"Aravindh, Chithambaram VR.",IND,M,GM,NaN,NaN,NaN,2723,8,10,1999
10710,13300474,"Aronian, Levon",USA,M,GM,NaN,NaN,NaN,2737,4,10,1982
29718,1503014,"Carlsen, Magnus",NOR,M,GM,NaN,NaN,NaN,2839,0,10,1990
30171,2020009,"Caruana, Fabiano",USA,M,GM,NaN,NaN,NaN,2784,0,10,1992
44707,8603677,"Ding, Liren",CHN,M,GM,NaN,NaN,NaN,2734,0,10,1992
45932,3503240,"Dominguez Perez, Leinier",USA,M,GM,NaN,NaN,NaN,2738,0,10,1983
47257,1170546,"Duda, Jan-Krzysztof",POL,M,GM,NaN,NaN,NaN,2725,0,10,1998
50403,35009192,Erigaisi Arjun,IND,M,GM,NaN,NaN,NaN,2776,0,10,2003
52788,24130737,"Fedoseev, Vladimir",SLO,M,GM,NaN,NaN,NaN,2731,8,10,1995
54563,12573981,"Firouzja, Alireza",FRA,M,GM,NaN,NaN,NaN,2766,0,10,2003
62146,24116068,"Giri, Anish",NED,M,GM,NaN,NaN,NaN,2748,0,10,1994
67122,46616543,Gukesh D,IND,M,GM,NaN,NaN,NaN,2776,0,10,2006
70032,5007003,"Harikrishna, Pentala",IND,M,GM,NaN,NaN,NaN,2709,0,10,1986
87083,12940690,"Keymer, Vincent",GER,M,GM,NaN,NaN,NaN,2730,0,10,2004
98577,12401137,"Le, Quang Liem",VIE,M,GM,NaN,"AO,FST",NaN,2729,0,10,1991
107471,13401319,"Mamedyarov, Shakhriyar",AZE,M,GM,NaN,NaN,NaN,2746,0,10,1985
123931,2016192,"Nakamura, Hikaru",USA,M,GM,NaN,NaN,NaN,2807,0,10,1987
125664,4168119,"Nepomniachtchi, Ian",RUS,M,GM,NaN,NaN,NaN,2742,0,10,1990
126970,2093596,"Niemann, Hans Moke",USA,M,GM,NaN,NaN,NaN,2736,0,10,2003
142407,25059530,Praggnanandhaa R,IND,M,GM,NaN,NaN,NaN,2779,0,10,2005
147445,738590,"Rapport, Richard",HUN,M,GM,NaN,NaN,NaN,2716,9,10,1996
167687,14205483,"Sindarov, Javokhir",UZB,M,GM,NaN,NaN,NaN,2722,0,10,2005
169397,5202213,"So, Wesley",USA,M,GM,NaN,NaN,NaN,2745,0,10,1993
180852,2900084,"Topalov, Veselin",BUL,M,GM,NaN,NaN,NaN,2717,0,10,1975
184785,623539,"Vachier-Lagrave, Maxime",FRA,M,GM,NaN,NaN,NaN,2736,0,10,1990
189352,5029465,"Vidit, Santosh Gujrathi",IND,M,GM,NaN,NaN,NaN,2720,0,10,1994
193406,8603405,"Wei, Yi",CHN,M,GM,NaN,NaN,NaN,2753,4,10,1999
197371,8603820,"Yu, Yangyi",CHN,M,GM,NaN,NaN,NaN,2714,0,10,1994

In [42]:
df.query("rating >=2750")

,id,name,fed,sex,title,wtitle,otitle,foa,rating,games,k,bday
986,14204118,"Abdusattorov, Nodirbek",UZB,M,GM,NaN,NaN,NaN,2771,0,10,2004
29718,1503014,"Carlsen, Magnus",NOR,M,GM,NaN,NaN,NaN,2839,0,10,1990
30171,2020009,"Caruana, Fabiano",USA,M,GM,NaN,NaN,NaN,2784,0,10,1992
50403,35009192,Erigaisi Arjun,IND,M,GM,NaN,NaN,NaN,2776,0,10,2003
54563,12573981,"Firouzja, Alireza",FRA,M,GM,NaN,NaN,NaN,2766,0,10,2003
67122,46616543,Gukesh D,IND,M,GM,NaN,NaN,NaN,2776,0,10,2006
123931,2016192,"Nakamura, Hikaru",USA,M,GM,NaN,NaN,NaN,2807,0,10,1987
142407,25059530,Praggnanandhaa R,IND,M,GM,NaN,NaN,NaN,2779,0,10,2005
193406,8603405,"Wei, Yi",CHN,M,GM,NaN,NaN,NaN,2753,4,10,1999

In [43]:
df.query("rating>=2500 and sex=='F'")

,id,name,fed,sex,title,wtitle,otitle,foa,rating,games,k,bday
11784,13708694,"Assaubayeva, Bibisara",KAZ,F,GM,WGM,NaN,NaN,2505,0,10,2004
48216,13601903,"Dzagnidze, Nana",GEO,F,GM,WGM,NaN,NaN,2500,8,10,1987
64624,4147103,"Goryachkina, Aleksandra",FID,F,GM,WGM,NaN,NaN,2528,2,10,1998
74786,8602980,"Hou, Yifan",CHN,F,GM,WGM,NaN,NaN,2609,9,10,1994
82244,8603006,"Ju, Wenjun",CHN,F,GM,WGM,NaN,NaN,2570,0,10,1991
90819,5008123,"Koneru, Humpy",IND,F,GM,WGM,NaN,NaN,2535,12,10,1987
96246,14109336,"Lagno, Kateryna",RUS,F,GM,WGM,NaN,NaN,2505,6,10,1989
99351,8605114,"Lei, Tingjie",CHN,F,GM,WGM,NaN,NaN,2565,12,10,1997
123148,14111330,"Muzychuk, Anna",UKR,F,GM,WGM,NaN,NaN,2535,4,10,1990
177138,8603642,"Tan, Zhongyi",CHN,F,GM,WGM,NaN,NaN,2539,12,10,1991
199759,8608059,"Zhu, Jiner",CHN,F,GM,WGM,NaN,NaN,2536,6,10,2002

| Rating     | Level                              |
| ---------- | ---------------------------------- |
| Below 1000 | Beginner                           |
| 1000–1200  | New player                         |
| 1200–1400  | Casual club player                 |
| 1400–1600  | Decent amateur                     |
| 1600–1800  | Strong club player                 |
| 1800–2000  | Very strong club player            |
| 2000–2200  | Expert                             |
| 2200–2400  | National Master level              |
| 2400–2500  | International Master (IM) strength |
| 2500+      | Grandmaster (GM) strength          |

In [60]:
 (df2[(df2["title"] == "GM")&(df2["rating"] >= 2700)])

,id,name,fed,sex,title,wtitle,otitle,foa,rating,games,k,bday
7612,5000017,"Anand, Viswanathan",IND,M,GM,NaN,NaN,NaN,2743,0,10,1969
9766,5072786,"Aravindh, Chithambaram VR.",IND,M,GM,NaN,NaN,NaN,2723,8,10,1999
50403,35009192,Erigaisi Arjun,IND,M,GM,NaN,NaN,NaN,2776,0,10,2003
67122,46616543,Gukesh D,IND,M,GM,NaN,NaN,NaN,2776,0,10,2006
70032,5007003,"Harikrishna, Pentala",IND,M,GM,NaN,NaN,NaN,2709,0,10,1986
142407,25059530,Praggnanandhaa R,IND,M,GM,NaN,NaN,NaN,2779,0,10,2005
189352,5029465,"Vidit, Santosh Gujrathi",IND,M,GM,NaN,NaN,NaN,2720,0,10,1994

In [78]:
 ((df2["title"] == "GM") &
    (df2["rating"] >= 2700)).sum()

np.int64(7)

In [62]:
 ((df["title"] == "GM") &
 (df["rating"] >= 2700)).sum()

np.int64(30)

In [84]:
(df["title"]=="GM")#it show with true or false

0         False
1         False
2         False
3         False
4         False
          ...
201010    False
201011    False
201012    False
201013    False
201014    False
Name: title, Length: 201015, dtype: bool

In [85]:
(df["title"]=="GM").sum()

np.int64(1306)

In [86]:
(df2["title"]=="GM").sum()

np.int64(67)