In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "EmpID":[101,102,103,104,105,105,107,108,109,110],
    "Name":["Abhay","Alok","Ravi","Neha","Priya","Priya","Aman","Kiran",np.nan,"Sonia"],
    "Department":["IT","HR","IT","Sales","HR","HR","IT",np.nan,"Sales","IT"],
    "Salary":[50000,45000,np.nan,55000,48000,48000,60000,52000,51000,np.nan],
    "Age":[25,28,30,np.nan,27,27,35,29,31,26],
    "City":["Delhi","Mumbai","Delhi","Patna","Mumbai","Mumbai","Delhi","Patna",np.nan,"Delhi"]
})

print(df)

   EmpID   Name Department   Salary   Age    City
0    101  Abhay         IT  50000.0  25.0   Delhi
1    102   Alok         HR  45000.0  28.0  Mumbai
2    103   Ravi         IT      NaN  30.0   Delhi
3    104   Neha      Sales  55000.0   NaN   Patna
4    105  Priya         HR  48000.0  27.0  Mumbai
5    105  Priya         HR  48000.0  27.0  Mumbai
6    107   Aman         IT  60000.0  35.0   Delhi
7    108  Kiran        NaN  52000.0  29.0   Patna
8    109    NaN      Sales  51000.0  31.0     NaN
9    110  Sonia         IT      NaN  26.0   Delhi

In [2]:
df.isnull()

   EmpID   Name  Department  Salary    Age   City
0  False  False       False   False  False  False
1  False  False       False   False  False  False
2  False  False       False    True  False  False
3  False  False       False   False   True  False
4  False  False       False   False  False  False
5  False  False       False   False  False  False
6  False  False       False   False  False  False
7  False  False        True   False  False  False
8  False   True       False   False  False   True
9  False  False       False    True  False  False

In [5]:
df.isnull().sum()

EmpID         0
Name          1
Department    1
Salary        2
Age           1
City          1
dtype: int64

In [4]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7    False
8    False
9    False
dtype: bool

In [8]:
df2=df.drop_duplicates().copy()

In [9]:
df2

   EmpID   Name Department   Salary   Age    City
0    101  Abhay         IT  50000.0  25.0   Delhi
1    102   Alok         HR  45000.0  28.0  Mumbai
2    103   Ravi         IT      NaN  30.0   Delhi
3    104   Neha      Sales  55000.0   NaN   Patna
4    105  Priya         HR  48000.0  27.0  Mumbai
6    107   Aman         IT  60000.0  35.0   Delhi
7    108  Kiran        NaN  52000.0  29.0   Patna
8    109    NaN      Sales  51000.0  31.0     NaN
9    110  Sonia         IT      NaN  26.0   Delhi

In [11]:
df2.isnull().sum()

EmpID         0
Name          1
Department    1
Salary        2
Age           1
City          1
dtype: int64

In [12]:
df2=df2.dropna()

In [13]:
df2

   EmpID   Name Department   Salary   Age    City
0    101  Abhay         IT  50000.0  25.0   Delhi
1    102   Alok         HR  45000.0  28.0  Mumbai
4    105  Priya         HR  48000.0  27.0  Mumbai
6    107   Aman         IT  60000.0  35.0   Delhi

In [16]:
df2.reset_index(drop=True,inplace=True) # this dirctly not print for print df2

In [15]:
df2

   EmpID   Name Department   Salary   Age    City
0    101  Abhay         IT  50000.0  25.0   Delhi
1    102   Alok         HR  45000.0  28.0  Mumbai
2    105  Priya         HR  48000.0  27.0  Mumbai
3    107   Aman         IT  60000.0  35.0   Delhi

In [27]:
# df2["Sex"]=df2["Name"].apply( lambda x : "Female" if x=="Priya" else "Male")
#or
df2.loc[:,"Sex"]=["Male","Male","Female","Male"]

In [18]:
df2

   EmpID   Name Department   Salary   Age    City     Sex
0    101  Abhay         IT  50000.0  25.0   Delhi    Male
1    102   Alok         HR  45000.0  28.0  Mumbai    Male
2    105  Priya         HR  48000.0  27.0  Mumbai  Female
3    107   Aman         IT  60000.0  35.0   Delhi    Male

In [22]:
df2.loc[:,"Experience"]=["0Y","3Y","1Y","5Y"]#means all row of experience column

In [23]:
df2

   EmpID   Name Department   Salary   Age    City     Sex Experience
0    101  Abhay         IT  50000.0  25.0   Delhi    Male         0Y
1    102   Alok         HR  45000.0  28.0  Mumbai    Male         3Y
2    105  Priya         HR  48000.0  27.0  Mumbai  Female         1Y
3    107   Aman         IT  60000.0  35.0   Delhi    Male         5Y

In [28]:
df2.loc[:,"Joindate"]=["01/06/2026","20/05/2023","15/04/2025","05/08/2021"]

C:\Users\Dipak Kumar\AppData\Local\Temp\ipykernel_4260\939725169.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.loc[:,"Joindate"]=["01/06/2026","20/05/2023","15/04/2025","05/08/2021"]

In [30]:
df2.loc[:,"Company"]=["Adobe","HP","Tata Motor","Nvidia"]

C:\Users\Dipak Kumar\AppData\Local\Temp\ipykernel_4260\1047010817.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.loc[:,"Company"]=["Adobe","HP","Tata Motor","Nvidia"]

In [31]:
df2

,EmpID,Name,Department,Salary,Age,City,Sex,Experience,Joindate,Company
0,101,Abhay,IT,50000.0,25.0,Delhi,Male,0Y,01/06/2026,Adobe
1,102,Alok,HR,45000.0,28.0,Mumbai,Male,3Y,20/05/2023,HP
2,105,Priya,HR,48000.0,27.0,Mumbai,Female,1Y,15/04/2025,Tata Motor
3,107,Aman,IT,60000.0,35.0,Delhi,Male,5Y,05/08/2021,Nvidia

In [33]:
df2.groupby("Department")["Salary"].mean()

Department
HR    46500.0
IT    55000.0
Name: Salary, dtype: float64

In [35]:
df2.groupby("Sex")["Salary"].mean()

Sex
Female    48000.000000
Male      51666.666667
Name: Salary, dtype: float64

In [40]:
df2["Rank"]=df2["Salary"].rank(ascending=False).astype(int)

C:\Users\Dipak Kumar\AppData\Local\Temp\ipykernel_4260\2634123170.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Rank"]=df2["Salary"].rank(ascending=False).astype(int)

In [41]:
df2

,EmpID,Name,Department,Salary,Age,City,Sex,Experience,Joindate,Company,Rank
0,101,Abhay,IT,50000.0,25.0,Delhi,Male,0Y,01/06/2026,Adobe,2
1,102,Alok,HR,45000.0,28.0,Mumbai,Male,3Y,20/05/2023,HP,4
2,105,Priya,HR,48000.0,27.0,Mumbai,Female,1Y,15/04/2025,Tata Motor,3
3,107,Aman,IT,60000.0,35.0,Delhi,Male,5Y,05/08/2021,Nvidia,1

In [ ]:
df2.groupby(